### ISSUE TITLE
老哥你这个用不了啊

### ISSUE THREAD

**Issue by cweijan** [Willing-Xyz/RestDoc#1]
看了你这个项目感觉很不错, 但是用了后发现无法解析javadoc, 我在自己的项目中测试不行, 运行demo也是同样的结果, 请问这是什么原因呢

![1](https://user-images.githubusercontent.com/27798227/62361898-82ea9900-b54e-11e9-8b4a-8fa9e446ac3f.png)
![2](https://user-images.githubusercontent.com/27798227/62361899-83832f80-b54e-11e9-9556-2d85d1947bd4.png)

这个是运行Demo的, docJson也有生成

**Comment by Willing-Xyz** [comment]
启动没问题是吧？你本机的demo打不开 这个地址吗 ：http://localhost:8084/swagger-ui/index.html

**Comment by Willing-Xyz** [comment]
老哥，你访问的可能是springfox的swagger-ui界面，那个是用于对照查看的。
你应该访问 这个路径 /swagger-ui/index.html，springfox的路径是 /swagger-ui.html

**Comment by cweijan** [comment]
确实可以了, 非常酷
