### ISSUE TITLE
restful风格bug

### ISSUE THREAD

**Issue by zt1820057934** [Willing-Xyz/RestDoc#10]
你好，swagger我一窍不通，我发现个问题，我有两个接口，一个是PostMapping("/v2/studio/department"),另一个是PutMapping("/v2/studio/department"),但是在swagger页面上只会显示一个，然后我就去看源码，发现openApi的path是一个map,key是路径，value是其它信息，而这两个接口路径是一样的，后一个会把前一个覆盖掉,请问怎么解决？
<img width="615" alt="屏幕快照 2019-09-20 上午12 10 27" src="https://user-images.githubusercontent.com/31762662/65261650-4f35f380-db3b-11e9-930e-7d4ddc058260.png">

**Comment by Willing-Xyz** [comment]
已修复，发布了0.1.7.1版本（maven依赖可能过段时间才能够生效）
