### ISSUE TITLE
api中不显示集合类参数

### ISSUE THREAD

**Issue by zt1820057934** [Willing-Xyz/RestDoc#12]
你好，不知为什么，它不显示集合类参数，list类不显示，set类只显示是否为空，其他的没试过.
<img width="602" alt="截屏2019-10-14上午10 49 22" src="https://user-images.githubusercontent.com/31762662/66727299-d5aad000-ee70-11e9-98a1-ec43808d036e.png">
<img width="473" alt="截屏2019-10-14上午10 49 34" src="https://user-images.githubusercontent.com/31762662/66727301-d80d2a00-ee70-11e9-91c0-907f4f85aa18.png">
<img width="697" alt="截屏2019-10-14上午10 49 59" src="https://user-images.githubusercontent.com/31762662/66727305-dba0b100-ee70-11e9-9370-94e2918c943b.png">

**Comment by Willing-Xyz** [comment]
我试了一下，list可以显示，set有些问题，这个会之后修掉。

**Comment by Willing-Xyz** [comment]
我试了一下，list可以显示，set有些问题，这个会之后修掉。
不知道你是不是直接在这个项目代码里改的，如果是的话，demoList字段要加下划线，因为lombok我配置了字段以下划线开始

**Comment by zt1820057934** [comment]
确实忘了加下划线了,3Q
