### ISSUE TITLE
建议增加example功能

### ISSUE THREAD

**Issue by cweijan** [Willing-Xyz/RestDoc#24]
Swagger注解有个example属性, 可以设置返回值的参考返回值, 建议向ignoreApi一样, 增加一个注解, 然后就可以通过注解设置参数的example
![image](https://user-images.githubusercontent.com/27798227/69474943-113aa180-0e02-11ea-84a5-8663d7f9916d.png)

**Comment by Willing-Xyz** [comment]
@cweijan 0.2.0.0-beta版本实现了这个功能，可以先试用看看  
https://github.com/Willing-Xyz/RestDoc/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89example

**Comment by cweijan** [comment]
ok. 我去试下

**Comment by cweijan** [comment]
貌似无效

**Comment by Willing-Xyz** [comment]
你可以试试RestDocSpringExamples模块里的 ExampleController

**Comment by cweijan** [comment]
#30
