### ISSUE TITLE
0.2.0.0-beta1  POST 请求的 @Valid 解析有误

### ISSUE THREAD

**Issue by tomgao365** [Willing-Xyz/RestDoc#29]
这些加了 @NotNull @NotBlank 等注解的字段未加 required ？

![image](https://user-images.githubusercontent.com/13798931/70369011-ca62a680-18ed-11ea-894a-16a2385f2db7.png)

**Comment by Willing-Xyz** [comment]
@tomgao365 改掉了。不过Generator有点乱，已经看不懂了😂，有时间要再整理一下

**Comment by tomgao365** [comment]
@Willing-Xyz 代码注释需要加起来了。
