### ISSUE TITLE
@RequestMapping使用了method指定了POST方法，还是解析了全部的方法

### ISSUE THREAD

**Issue by 302819524** [Willing-Xyz/RestDoc#3]
您好，我看了SpringMethodParser类中
if (annotationType == RequestMapping.class) {
                var requestMappingAnno = (RequestMapping) annotation;
                methods = new RequestMethod[]{GET, POST, PUT, DELETE, OPTIONS, PATCH, HEAD};
                mappingPaths = requestMappingAnno.path();
                mappingValues = requestMappingAnno.value();
            }
没有对method属性进行解析
建议添加对method属性解析的支持
最后还是感谢将代码开源出来

**Comment by Willing-Xyz** [comment]
感谢关注。 03889c9adc15ad113069859994d66f654c3328c8 已修复
