### ISSUE TITLE
代码格式疑惑

### ISSUE THREAD

**Issue by cweijan** [Willing-Xyz/RestDoc#31]
目前一些新的代码左花括号都换行了, 这是为什么? 你是C#派来的间谍吗?
![image](https://user-images.githubusercontent.com/27798227/70418758-ff622b00-1a9e-11ea-9c3f-6260a73c7d4c.png)

**Comment by Willing-Xyz** [comment]
还真写过挺长时间的C#😂。
我写代码是换行的，因为我用的vim插件，换行比不换行方便多了。
只是有时候会格式化代码，就变成不换行了。
我觉得不换行挺好的
