### ISSUE TITLE
这简直太棒了

### ISSUE THREAD

**Issue by wenwenbaba** [Willing-Xyz/RestDoc#32]
大佬的开源真是令人兴奋啊.
解决了我一个大问题.
谢谢.

然后我希望:
再加上对webservice的支持就更好了.
我尝试着阅读源码,用来模拟webservice.
如果大佬有空,也希望可以去做.

**Comment by Willing-Xyz** [comment]
感谢使用和反馈.
可以参考wiki：https://github.com/Willing-Xyz/RestDoc/wiki/%E8%AE%BE%E8%AE%A1%E4%B8%8E%E6%89%A9%E5%B1%95
代码方面可以参考RestDocSpring模块
