### ISSUE TITLE
建议作者把软件信息发布到开源中国和掘金这些网站

### ISSUE THREAD

**Issue by tomgao365** [Willing-Xyz/RestDoc#34]
感谢作者做的**RestDoc**，这是一个很棒的软件。建议作者把它发布到[开源中国](https://www.oschina.net/)和[掘金](https://juejin.im/timeline)，让更多的人了解和使用它。

**Comment by Willing-Xyz** [comment]
我记得有发布到segmentFault、掘金和简书，其他还没有发布

**Comment by tomgao365** [comment]
版本迭代了，也发布，刷刷存在感。

**Comment by Willing-Xyz** [comment]
对，release忘了写，其他的就顺其自然了
