### ISSUE TITLE
@JsonIgnoreProperties 解析有些问题

### ISSUE THREAD

**Issue by tomgao365** [Willing-Xyz/RestDoc#36]
比如 ClassA 使用了该注解，ClassB 继承 ClassA ，ClassB 实例序列化后，ClassA 的@JsonIgnoreProperties 中忽略字段仍然存在

**Comment by Willing-Xyz** [comment]
你看一下 项目里 JacksonController 这个例子
![image](https://user-images.githubusercontent.com/12200332/79863296-154b0980-840a-11ea-89bd-0d1294cd79ce.png)
我看它解析的没有问题，能不能把你代码贴出来看一下？

**Comment by tomgao365** [comment]
我用了 Mybatis Plus 的分页类[Page](https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/plugins/pagination/Page.java#L355)，可能是因为参数名和方法名命名相同的原因造成的。

```java
@JsonIgnoreProperties({"current", "size", "orders", "hitCount", "searchCount", "pages"})
public class MyPage<T> extends Page<T> {
}
```
写个接口将 `MyPage<String>` 作为返回值
postman调试接口如下：
![image](https://user-images.githubusercontent.com/13798931/79871166-914b4e80-8416-11ea-888b-f6cea5c254aa.png)

解析的 swagger 如下：
![image](https://user-images.githubusercontent.com/13798931/79871133-8395c900-8416-11ea-8510-1ea57c59d335.png)

**Comment by Willing-Xyz** [comment]
是个bug，有些情况没有处理到。0.2.1.3版本修复了

**Comment by tomgao365** [comment]
maven 仓库里都没有这个版本。上个版本的也没发，忘了发了？😂

**Comment by tomgao365** [comment]
@Willing-Xyz 已升级到了最新版，问题仍然存在。
```java
// 统一返回对象如下
@Data
@Accessors(chain = true)
public class R<T> implements Serializable {
    private long code;
    private T data;
    private String msg;
}
// 用户信息
@Data
@Accessors(chain = true)
public class User implements Serializable {
    private String name;
}
```
RestController 调用代码如下
```java
    @GetMapping("/page")
    public R<MyPage<User>> page() {
        return null;
    }
```

**Comment by Willing-Xyz** [comment]
发布后，同步到中央仓库需要大概几个小时吧。不过上一个版本确实忘了传😂。
0.2.1.4版本试试

**Comment by tomgao365** [comment]
maven 仓库还是木有0.2.1.4，估计下午或晚上再验证。

**Comment by tomgao365** [comment]
Good,问题解决了。
