### ISSUE TITLE
controller方法中存在HttpServletRequest request, HttpServletResponse response也会同时解析

### ISSUE THREAD

**Issue by 302819524** [Willing-Xyz/RestDoc#4]
首先感谢将代码分享出来
实际发送参数的时候request和response，不需要填写这两个参数。在使用springfox-swagger2的时候，它解析时就会过滤掉request和response。
希望可以支持过滤

**Comment by Willing-Xyz** [comment]
这个问题可以描述详细一点吗，有点不太明白？

**Comment by 302819524** [comment]
比如这个请求方法
`@PostMapping("/upgrade")
 public void upgrade(@RequestBody @Validated UpgradeInfoBo upgradeInfo, HttpServletRequest request, HttpServletResponse response){}`
在使用index.html页面进行tyr it out的时候，会把request和response当成一个普通的对象将属性也解析出来。但实际我们进行测试传参的时候是不需要关系request和response的

**Comment by Willing-Xyz** [comment]
感谢关注。 03889c9adc15ad113069859994d66f654c3328c8 已修复
