### ISSUE TITLE
自带的SwaggerUI太丑太难用，是否可以更换为Knife4j？

### ISSUE THREAD

**Issue by dadiyang** [Willing-Xyz/RestDoc#42]
我们试图使用 Knife4j 来显示 RestDoc 生成的 swagger 信息，但是 Knife4j 是基于 /v2/api-docs 或者它自定义的 /v2/api-docs-ext 接口，而咱们这个项目只改写了 swagger.json 接口，因此结合不起来。如果是合起来，就太棒了！

**Comment by Willing-Xyz** [comment]
你可以考虑在自己的项目中转接一下接口，比如实现/v2/api-docs接口，这个接口实现调用swagger.json接口
