### ISSUE TITLE
考虑编译时生成javadoc的json文件单独放到一个文件夹中吗

### ISSUE THREAD

**Issue by 302819524** [Willing-Xyz/RestDoc#5]
首先感谢分享代码
现在注意到是和源码包放在一个文件夹下的，个人感觉源码包就是源码包还是得纯净一点，json文件可以单独在存一个文件夹

**Comment by Willing-Xyz** [comment]
当前生成和解析javadoc都是使用 therapi-runtime-javadoc 这个库来处理的。
短时间内还没有修改这方面的打算。

**Comment by 302819524** [comment]
好的，谢谢
