### ISSUE TITLE
可以分模块起作用吗?

### ISSUE THREAD

**Issue by zt1820057934** [Willing-Xyz/RestDoc#9]
你好，这个特别好用，解决了代码的入侵性，我这有个问题，在springboot项目中，新建一个A模块专门用来弄swagger，里面有配置和依赖，然后用自动装配，在B模块(Controller层)引用，但是导不出json，必须在B模块pom里加javadoc依赖，而B模块又引用C模块(model层),C模块里的又不起作用，请问大牛 必须每个模块都得加那个依赖吗，还是有更好的办法？

**Comment by Willing-Xyz** [comment]
你好，导不出json是指 没有生成 javadoc的json文件吗？然后你说的每个模块都必须增加依赖，这个依赖是指哪个依赖？是therapi-runtime-javadoc-scribe这个依赖吗？

**Comment by zt1820057934** [comment]
嗯，对对

**Comment by zt1820057934** [comment]
抱歉，有歧义，并不是导不出json，是json里没有java doc注释了

**Comment by Willing-Xyz** [comment]
![image](https://user-images.githubusercontent.com/12200332/65237225-ca33e580-db0c-11e9-8d68-07bf7a0efd50.png)
这样类似格式的文件有生成？但里面没内容？

**Comment by zt1820057934** [comment]
说错了，只有引入了therapi-runtime-javadoc-scribe依赖的模块才有这个json，里面注释正常，没引入这个依赖，就没有json

**Comment by Willing-Xyz** [comment]
确实是这样。只有引入了这个依赖才会生成json。
但如果你分模块的话，一般只有需要生成swagger的模块需要加这个依赖。

**Comment by Willing-Xyz** [comment]
另外。这个依赖只在编译时起作用，所以scope是provided

**Comment by zt1820057934** [comment]
嗯嗯，谢谢谢谢
